### ISSUE TITLE
Error encrytion items after upgrade from 2.1.23 to 2.1.24

### ISSUE THREAD

**Issue by Benny1988** [nilsteampassnet/TeamPass#2435]
### Steps to reproduce
1. Successful upgrade from 2.1.23 to 2.1.24
2. Encryption after Login
3. after that i cant see the passwords (red exclamation mark)

### Expected behaviour
Tell us what should happen:
Teampass should encrypt the passwords correctly and without errors.

### Actual behaviour
Tell us what happens instead
After the new encryption process i cant see the passwords and every entry has a red exclamation point.

### Server configuration
**Operating system**:
Debian Wheezy

**Web server:**
Apache/2.2.22 (Debian)

**Database:**
MySQL 5.5.60-0+deb7u1 (Debian)

**PHP version:**
5.5.38-1~dotdeb+7.1

**Teampass version:** 
2.1.23

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
I dont have this file.

### Client configuration
**Browser:**
Firefox 62.0.3

**Operating system:**
Linux Debian

#### Web server error log
```
[10-Oct-2018 13:15:57 Europe/Berlin] PHP Warning:  AES-128 requires a 16 byte key, 15 bytes received in /var/www/tkhpass/includes/libraries/phpcrypt/Cipher.php on line 245
[10-Oct-2018 13:15:57 Europe/Berlin] PHP Notice:  Uninitialized string offset: -16 in /var/www/tkhpass/includes/libraries/phpcrypt/ciphers/Rijndael.php on line 340
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
TypeError: (intermediate value).apply is not a function[Weitere Informationen] jquery.js:5094:15
dispatch
https://tkhpass2.tkh.local/includes/js/jquery-ui/external/jquery/jquery.js:5094:15
add/elemData.handle
https://tkhpass2.tkh.local/includes/js/jquery-ui/external/jquery/jquery.js:4766:6
_fillForm
resource://gre/modules/LoginManagerContent.jsm:1246:9
loginsFound
resource://gre/modules/LoginManagerContent.jsm:574:5
loginsFound self-hosted:987:17
```

**Comment by nilsteampassnet** [comment]
I believe that was solved by email directly

**Comment by nilsteampassnet** [comment]
Please reopen this ticket on need.

**Comment by Benny1988** [comment]
> I believe that was solved by email directly

What do you mean? Can't follow this answer.

**Comment by nilsteampassnet** [comment]
I though you were the person in discussed by email because you had exactly the same issue.

Here is what I proposed.

**2.1.23.4**

- perform the next SQL query:  `ALTER TABLE `teampass_misc` ADD `id` INT(12) NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`);`
- rename the file `/install/upgrade_ajax.php` by `/install/upgrade_ajax_original.php`
- copy the file `upgrade_ajax_pour_2.1.23.4.php `in the same folder and rename it to `upgrade_ajax.php`
- do migration
- check every thing works. If ok do a DB backup and folder backup

[upgrade_ajax_pour_2.1.23.4.php.zip](https://github.com/nilsteampassnet/TeamPass/files/2480104/upgrade_ajax_pour_2.1.23.4.php.zip)
	
**2.1.24.4**
	
- before starting, perform the SQL query:  I`NSERT INTO `teampass_misc` (`id`, `type`, `intitule`, `valeur`) VALUES (NULL, 'admin', 'encryption_protocol', 'ctr');`
- do migration
- check every thing works. If ok do a DB backup and folder backup	
	
**2.1.25.2**

- before starting, perform the SQL query: `ALTER TABLE `teampass_items` CHANGE `pw_len` `pw_len` INT(5) NOT NULL DEFAULT '0';`
- do migration
- check every thing works. If ok do a DB backup and folder backup	
	
**2.1.26-final-3**
	
- do migration
- check every thing works. If ok do a DB backup and folder backup	
	
**2.1.27.23**
	
- before starting, perform the SQL query: `ALTER TABLE `teampass_misc` CHANGE `id` `increment_id` INT(12) NOT NULL AUTO_INCREMENT;`
- do migration
- check every thing works (be sure to clear the browser cache). If ok do a DB backup and folder backup.


This has been successfully performed on users with the same error.

Please come back to me with your feedback.

**Comment by Benny1988** [comment]
I think i can close this issue. Out teampass works very well after this solutions. Thanks Nils.

**Comment by nilsteampassnet** [comment]
You are welcome

**Comment by albarki** [comment]
Hi @Benny1988, I am currently on version `2.1.23.4` and I am struggling to update to `2.1.24.2`, I did the following steps but still have that red exclamation mark says `Error Encryption of the password`
```
* perform the next SQL query:  `` ALTER TABLE `teampass_misc` ADD `id` INT(12) NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`); ``
* rename the file `/install/upgrade_ajax.php` by `/install/upgrade_ajax_original.php`
* copy the file `upgrade_ajax_pour_2.1.23.4.php`in the same folder and rename it to `upgrade_ajax.php`
* do migration
* check every thing works. If ok do a DB backup and folder backup
```

@Benny1988 can you please share with me the steps that you are followed to make it works?

Thanks 
Ibrahim

**Comment by Benny1988** [comment]
> Hi @Benny1988, I am currently on version `2.1.23.4` and I am struggling to update to `2.1.24.2`, I did the following steps but still have that red exclamation mark says `Error Encryption of the password`
> 
> ```
> * perform the next SQL query:  `` ALTER TABLE `teampass_misc` ADD `id` INT(12) NOT NULL AUTO_INCREMENT FIRST, ADD PRIMARY KEY (`id`); ``
> * rename the file `/install/upgrade_ajax.php` by `/install/upgrade_ajax_original.php`
> * copy the file `upgrade_ajax_pour_2.1.23.4.php`in the same folder and rename it to `upgrade_ajax.php`
> * do migration
> * check every thing works. If ok do a DB backup and folder backup
> ```
> 
> @Benny1988 can you please share with me the steps that you are followed to make it works?
> 
> Thanks
> Ibrahim

Sorry for the late reply. Maybe you already solved it? I did only the steps and it works.
